---
ID: "73bf12bb-7de2-4e52-a3a7-9b6aae0dd932"
Parent: "610a1783-8bda-4081-ad39-ee25be74707c"
Template: "610a1783-8bda-4081-ad39-ee25be74707c"
Path: /sitecore/templates/Feature/acceleratorcommunity/GridColumn/__Standard Values
SharedFields:
- ID: "1691ea75-1b5e-4720-a604-c8a8ac525069"
  Hint: heading
  Value: $name
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230306T154828Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8a9fe9ed-c62b-4ce2-9a6b-3472e059ca99"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230306T154839Z
