stages:
- deploy

deploy_preview:
 stage: deploy
 tags:
     - vercel
 image: node:16.16.0
 only:
  - GenericComponents
 script:
 - cd src/acceleratorcommunity
 - vercel pull --yes --environment=preview --token=L5Sr6ZrZzYcnkNPW7omJTSnJ
 - vercel build --prod --token=L5Sr6ZrZzYcnkNPW7omJTSnJ
 - vercel deploy --prebuilt --token=L5Sr6ZrZzYcnkNPW7omJTSnJ

deploy_production:
 stage: deploy
 tags:
     - vercel
 image: node:16.16.0
 only:
  - develop
 script:
 - cd src/acceleratorcommunity
 - vercel pull --yes --environment=production --token=L5Sr6ZrZzYcnkNPW7omJTSnJ
 - vercel build --prod --token=L5Sr6ZrZzYcnkNPW7omJTSnJ
 - vercel deploy --prebuilt --prod --token=L5Sr6ZrZzYcnkNPW7omJTSnJ