---
ID: "6136ae61-05f7-47b1-8056-39a982ba2a6b"
Parent: "0a24b14e-bbdd-4d84-8139-7d40e3b356fa"
Template: "0a24b14e-bbdd-4d84-8139-7d40e3b356fa"
Path: /sitecore/templates/Project/acceleratorcommunity/Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "03897511-7b06-4331-8ca0-1929bc3047ce"
      Hint: Navigation Title
      Value: $name
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{67200981-7579-4BC4-9F6A-75CB20338B43}"
              p:after="p[@uid='{B114D3F0-F504-51DF-B6BA-03D0FCEC087A}']"
              s:ds="{94AD1290-B1EA-4C4E-8507-B22B02E68B19}"
              s:id="{78BAF5D7-D604-454E-B796-8CBB67AA4FE2}"
              s:par="CSSStyles"
              s:ph="/jss-header/col3-{8A85A4E1-0C53-4C54-AB43-539E5DB92F09}-0"
              s:ccb="Clear on publish" />
            <r
              uid="{3555FF79-596B-433E-AD70-3747B743E69D}"
              p:after="r[@uid='{67200981-7579-4BC4-9F6A-75CB20338B43}']"
              s:ds="{A85E619F-7F82-4795-9E12-85783900263D}"
              s:id="{66B09AA5-3A20-4FB1-ABC2-D1AE2DF6BE09}"
              s:par="CSSStyles"
              s:ph="/jss-header/col3-{8A85A4E1-0C53-4C54-AB43-539E5DB92F09}-0"
              s:ccb="Clear on publish" />
            <r
              uid="{2D3DA198-27F1-491E-832A-8AC684D02D14}"
              p:after="r[@uid='{3555FF79-596B-433E-AD70-3747B743E69D}']"
              s:ds="{60828F2C-A954-413B-B5DE-FC77AF7C9F13}"
              s:id="{67F9F9E6-8533-467F-B7D7-13CC8EE7498F}"
              s:par="CSSStyles"
              s:ph="/jss-header/col2-{8A85A4E1-0C53-4C54-AB43-539E5DB92F09}-0"
              s:ccb="Clear on publish" />
            <r
              uid="{8A85A4E1-0C53-4C54-AB43-539E5DB92F09}"
              p:after="r[@uid='{2D3DA198-27F1-491E-832A-8AC684D02D14}']"
              s:ds="{AB3AEF4C-1276-4441-83D2-810D05708880}"
              s:id="{44F40912-35E3-43E6-8C36-6488DC75421E}"
              s:ph="jss-header" />
            <r
              uid="{73E733AA-0350-4EE5-9F9B-BF18421B77F0}"
              p:after="*[1=2]"
              s:ds="{D8B49499-193A-4E04-AEAE-BDD5F68A6189}"
              s:id="{6DC8C62B-AE1B-44F0-8506-FECF599C345B}"
              s:par="CSSStyles"
              s:ph="/jss-header/col1-{8A85A4E1-0C53-4C54-AB43-539E5DB92F09}-0"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230309T065926Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e005689-3ae2-495a-9108-0b01fbf0cd89"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\damyanti.wakchaure@nagarro.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230504T133108Z
