---
ID: "39442d8a-8cd6-4f8e-9faa-c32518159092"
Parent: "1e1007a3-1fde-46a1-9e2d-098a989ec0ec"
Template: "1e1007a3-1fde-46a1-9e2d-098a989ec0ec"
Path: /sitecore/templates/Project/acceleratorcommunity/Base Templates/_Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230313T102809Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "99e95014-7c97-4656-8900-0bf9f0b0ab30"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T102809Z
