---
ID: "5f92f6fd-fd67-4e0b-b64f-ab9902af56a7"
Parent: "97bb31a0-71aa-4d74-9a39-9ee902f26eb6"
Template: "97bb31a0-71aa-4d74-9a39-9ee902f26eb6"
Path: /sitecore/templates/Feature/acceleratorcommunity/ArticleContentType/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: People/16x16/masks.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230313T060449Z
    - ID: "35688228-4597-455c-aa58-c19662a04e5a"
      Hint: Name
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e798db0b-0e52-4466-9235-037f7ad6549f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T060520Z
