---
ID: "de44abb5-4ef9-46ea-a29c-72a4b59e57ea"
Parent: "c90d9ec6-e34d-4dbb-a884-180f53fea130"
Template: "c90d9ec6-e34d-4dbb-a884-180f53fea130"
Path: /sitecore/templates/Feature/acceleratorcommunity/ContentName/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Business/16x16/paperclip.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230313T060352Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eee1722d-54d5-4896-b6f8-8c8382c9f345"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T060430Z
    - ID: "f18b1a9a-d1ff-4c13-ad60-80a2f710e438"
      Hint: Name
      Value: $name
