---
ID: "1ad33f8e-68ac-484c-a1cc-bf956ecf7e0e"
Parent: "e0553632-ee1e-4894-88a1-9c1c201060ef"
Template: "e0553632-ee1e-4894-88a1-9c1c201060ef"
Path: /sitecore/templates/Feature/acceleratorcommunity/Rendering Parameters Template/AddPostRenderingParameter/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230502T095020Z
    - ID: "3813b1f3-c883-42c3-a5b5-7164774a64e8"
      Hint: URL
      Value: "https://accelerator-api-management.azure-api.net/graph-service/api/v1/graph/post"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\nishant.tiwari@nagarro.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\nishant.tiwari@nagarro.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6998333f-82a8-4f37-b3e6-d8c3c21c85ff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\nishant.tiwari@nagarro.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230502T110151Z
