---
ID: "d8d2fe9f-f68e-4c1f-9f8d-b580eb92c1cc"
Parent: "52e28ba5-3a3f-4227-88fc-0812e42cd12d"
Template: "52e28ba5-3a3f-4227-88fc-0812e42cd12d"
Path: /sitecore/templates/Project/acceleratorcommunity/Base Templates/_LandingBase/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230313T102541Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "51a7cc23-3bc4-45c4-bcce-1ef8eaa0ed06"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T102541Z
